import random

questions = [
    ["What is the 2nd degree of the C major scale?", "D"],
    ["What is the 3rd degree of the C major scale?", "E"],
    ["What is the 4th degree of the C major scale?", "F"],
    ["What is the 5th degree of the C major scale?", "G"],
    ["What is the 6th degree of the C major scale?", "A"],
    ["What is the 7th degree of the C major scale?", "B"],
    ["What is the 9th degree of the C major scale?", "D"],
    ["What is the 11th degree of the C major scale?", "F"],
    ["What is the 13th degree of the C major scale?", "A"],
    ["What is the 2nd degree of the A minor scale?", "B"],
    ["What is the 3rd degree of the A minor scale?", "C"],
    ["What is the 4th degree of the A minor scale?", "D"],
    ["What is the 5th degree of the A minor scale?", "E"],
    ["What is the 6th degree of the A minor scale?", "F"],
    ["What is the 7th degree of the A minor scale?", "G"],
    ["What is the 9th degree of the A minor scale?", "B"],
    ["What is the 11th degree of the A minor scale?", "D"],
    ["What is the 13th degree of the A minor scale?", "F"],
    ["What is the 2nd degree of the G major scale?", "A"],
    ["What is the 3rd degree of the G major scale?", "B"],
    ["What is the 4th degree of the G major scale?", "C"],
    ["What is the 5th degree of the G major scale?", "D"],
    ["What is the 6th degree of the G major scale?", "E"],
    ["What is the 7th degree of the G major scale?", "F#"],
    ["What is the 9th degree of the G major scale?", "A"],
    ["What is the 11th degree of the G major scale?", "C"],
    ["What is the 13th degree of the G major scale?", "E"],
    ["What is the 2nd degree of the E minor scale?", "F#"],
    ["What is the 3rd degree of the E minor scale?", "G"],
    ["What is the 4th degree of the E minor scale?", "A"],
    ["What is the 5th degree of the E minor scale?", "B"],
    ["What is the 6th degree of the E minor scale?", "C"],
    ["What is the 7th degree of the E minor scale?", "D"],
    ["What is the 9th degree of the E minor scale?", "F#"],
    ["What is the 11th degree of the E minor scale?", "A"],
    ["What is the 13th degree of the E minor scale?", "C"],
    ["What is the 2nd degree of the D major scale?", "E"],
    ["What is the 3rd degree of the D major scale?", "F#"],
    ["What is the 4th degree of the D major scale?", "G"],
    ["What is the 5th degree of the D major scale?", "A"],
    ["What is the 6th degree of the D major scale?", "B"],
    ["What is the 7th degree of the D major scale?", "C#"],
    ["What is the 9th degree of the D major scale?", "E"],
    ["What is the 11th degree of the D major scale?", "G"],
    ["What is the 13th degree of the D major scale?", "B"],
    ["What is the 2nd degree of the B minor scale?", "C#"],
    ["What is the 3rd degree of the B minor scale?", "D"],
    ["What is the 4th degree of the B minor scale?", "E"],
    ["What is the 5th degree of the B minor scale?", "F#"],
    ["What is the 6th degree of the B minor scale?", "G"],
    ["What is the 7th degree of the B minor scale?", "A"],
    ["What is the 9th degree of the B minor scale?", "C#"],
    ["What is the 11th degree of the B minor scale?", "E"],
    ["What is the 13th degree of the B minor scale?", "G"],
    ["What is the 2nd degree of the A major scale?", "B"],
    ["What is the 3rd degree of the A major scale?", "C#"],
    ["What is the 4th degree of the A major scale?", "D"],
    ["What is the 5th degree of the A major scale?", "E"],
    ["What is the 6th degree of the A major scale?", "F#"],
    ["What is the 7th degree of the A major scale?", "G#"],
    ["What is the 9th degree of the A major scale?", "B"],
    ["What is the 11th degree of the A major scale?", "D"],
    ["What is the 13th degree of the A major scale?", "F#"],
    ["What is the 2nd degree of the F# minor scale?", "G#"],
    ["What is the 3rd degree of the F# minor scale?", "A"],
    ["What is the 4th degree of the F# minor scale?", "B"],
    ["What is the 5th degree of the F# minor scale?", "C#"],
    ["What is the 6th degree of the F# minor scale?", "D"],
    ["What is the 7th degree of the F# minor scale?", "E"],
    ["What is the 9th degree of the F# minor scale?", "G#"],
    ["What is the 11th degree of the F# minor scale?", "B"],
    ["What is the 13th degree of the F# minor scale?", "D"],
    ["What is the 2nd degree of the E major scale?", "F#"],
    ["What is the 3rd degree of the E major scale?", "G#"],
    ["What is the 4th degree of the E major scale?", "A"],
    ["What is the 5th degree of the E major scale?", "B"],
    ["What is the 6th degree of the E major scale?", "C#"],
    ["What is the 7th degree of the E major scale?", "D#"],
    ["What is the 9th degree of the E major scale?", "F#"],
    ["What is the 11th degree of the E major scale?", "A"],
    ["What is the 13th degree of the E major scale?", "C#"],
    ["What is the 2nd degree of the C# minor scale?", "D#"],
    ["What is the 3rd degree of the C# minor scale?", "E"],
    ["What is the 4th degree of the C# minor scale?", "F#"],
    ["What is the 5th degree of the C# minor scale?", "G#"],
    ["What is the 6th degree of the C# minor scale?", "A"],
    ["What is the 7th degree of the C# minor scale?", "B"],
    ["What is the 9th degree of the C# minor scale?", "D#"],
    ["What is the 11th degree of the C# minor scale?", "F#"],
    ["What is the 13th degree of the C# minor scale?", "A"],
    ["What is the 2nd degree of the B major scale?", "C#"],
    ["What is the 3rd degree of the B major scale?", "D#"],
    ["What is the 4th degree of the B major scale?", "E"],
    ["What is the 5th degree of the B major scale?", "F#"],
    ["What is the 6th degree of the B major scale?", "G#"],
    ["What is the 7th degree of the B major scale?", "A#"],
    ["What is the 9th degree of the B major scale?", "C#"],
    ["What is the 11th degree of the B major scale?", "E"],
    ["What is the 13th degree of the B major scale?", "G#"],
    ["What is the 2nd degree of the G# minor scale?", "A#"],
    ["What is the 3rd degree of the G# minor scale?", "B"],
    ["What is the 4th degree of the G# minor scale?", "C#"],
    ["What is the 5th degree of the G# minor scale?", "D#"],
    ["What is the 6th degree of the G# minor scale?", "E"],
    ["What is the 7th degree of the G# minor scale?", "F#"],
    ["What is the 9th degree of the G# minor scale?", "A#"],
    ["What is the 11th degree of the G# minor scale?", "C#"],
    ["What is the 13th degree of the G# minor scale?", "E"],
    ["What is the 2nd degree of the F# major scale?", "G#"],
    ["What is the 3rd degree of the F# major scale?", "A#"],
    ["What is the 4th degree of the F# major scale?", "B"],
    ["What is the 5th degree of the F# major scale?", "C#"],
    ["What is the 6th degree of the F# major scale?", "D#"],
    ["What is the 7th degree of the F# major scale?", "E#"],
    ["What is the 9th degree of the F# major scale?", "G#"],
    ["What is the 11th degree of the F# major scale?", "B"],
    ["What is the 13th degree of the F# major scale?", "D#"],
    ["What is the 2nd degree of the D# minor scale?", "E#"],
    ["What is the 3rd degree of the D# minor scale?", "F#"],
    ["What is the 4th degree of the D# minor scale?", "G#"],
    ["What is the 5th degree of the D# minor scale?", "A#"],
    ["What is the 6th degree of the D# minor scale?", "B"],
    ["What is the 7th degree of the D# minor scale?", "C#"],
    ["What is the 9th degree of the D# minor scale?", "E#"],
    ["What is the 11th degree of the D# minor scale?", "G#"],
    ["What is the 13th degree of the D# minor scale?", "B"],
    ["What is the 2nd degree of the F major scale?", "G"],
    ["What is the 3rd degree of the F major scale?", "A"],
    ["What is the 4th degree of the F major scale?", "Bb"],
    ["What is the 5th degree of the F major scale?", "C"],
    ["What is the 6th degree of the F major scale?", "D"],
    ["What is the 7th degree of the F major scale?", "E"],
    ["What is the 9th degree of the F major scale?", "G"],
    ["What is the 11th degree of the F major scale?", "Bb"],
    ["What is the 13th degree of the F major scale?", "D"],
    ["What is the 2nd degree of the D minor scale?", "E"],
    ["What is the 3rd degree of the D minor scale?", "F"],
    ["What is the 4th degree of the D minor scale?", "G"],
    ["What is the 5th degree of the D minor scale?", "A"],
    ["What is the 6th degree of the D minor scale?", "Bb"],
    ["What is the 7th degree of the D minor scale?", "C"],
    ["What is the 9th degree of the D minor scale?", "E"],
    ["What is the 11th degree of the D minor scale?", "G"],
    ["What is the 13th degree of the D minor scale?", "Bb"],
    ["What is the 2nd degree of the Bb major scale?", "C"],
    ["What is the 3rd degree of the Bb major scale?", "D"],
    ["What is the 4th degree of the Bb major scale?", "Eb"],
    ["What is the 5th degree of the Bb major scale?", "F"],
    ["What is the 6th degree of the Bb major scale?", "G"],
    ["What is the 7th degree of the Bb major scale?", "A"],
    ["What is the 9th degree of the Bb major scale?", "C"],
    ["What is the 11th degree of the Bb major scale?", "Eb"],
    ["What is the 13th degree of the Bb major scale?", "G"],
    ["What is the 2nd degree of the G minor scale?", "A"],
    ["What is the 3rd degree of the G minor scale?", "Bb"],
    ["What is the 4th degree of the G minor scale?", "C"],
    ["What is the 5th degree of the G minor scale?", "D"],
    ["What is the 6th degree of the G minor scale?", "Eb"],
    ["What is the 7th degree of the G minor scale?", "F"],
    ["What is the 9th degree of the G minor scale?", "A"],
    ["What is the 11th degree of the G minor scale?", "C"],
    ["What is the 13th degree of the G minor scale?", "Eb"],
    ["What is the 2nd degree of the Eb major scale?", "F"],
    ["What is the 3rd degree of the Eb major scale?", "G"],
    ["What is the 4th degree of the Eb major scale?", "Ab"],
    ["What is the 5th degree of the Eb major scale?", "Bb"],
    ["What is the 6th degree of the Eb major scale?", "C"],
    ["What is the 7th degree of the Eb major scale?", "D"],
    ["What is the 9th degree of the Eb major scale?", "F"],
    ["What is the 11th degree of the Eb major scale?", "Ab"],
    ["What is the 13th degree of the Eb major scale?", "C"],
    ["What is the 2nd degree of the C minor scale?", "D"],
    ["What is the 3rd degree of the C minor scale?", "Eb"],
    ["What is the 4th degree of the C minor scale?", "F"],
    ["What is the 5th degree of the C minor scale?", "G"],
    ["What is the 6th degree of the C minor scale?", "Ab"],
    ["What is the 7th degree of the C minor scale?", "Bb"],
    ["What is the 9th degree of the C minor scale?", "D"],
    ["What is the 11th degree of the C minor scale?", "F"],
    ["What is the 13th degree of the C minor scale?", "Ab"],
    ["What is the 2nd degree of the Ab major scale?", "Bb"],
    ["What is the 3rd degree of the Ab major scale?", "C"],
    ["What is the 4th degree of the Ab major scale?", "Db"],
    ["What is the 5th degree of the Ab major scale?", "Eb"],
    ["What is the 6th degree of the Ab major scale?", "F"],
    ["What is the 7th degree of the Ab major scale?", "G"],
    ["What is the 9th degree of the Ab major scale?", "Bb"],
    ["What is the 11th degree of the Ab major scale?", "Db"],
    ["What is the 13th degree of the Ab major scale?", "F"],
    ["What is the 2nd degree of the F minor scale?", "G"],
    ["What is the 3rd degree of the F minor scale?", "Ab"],
    ["What is the 4th degree of the F minor scale?", "Bb"],
    ["What is the 5th degree of the F minor scale?", "C"],
    ["What is the 6th degree of the F minor scale?", "Db"],
    ["What is the 7th degree of the F minor scale?", "Eb"],
    ["What is the 9th degree of the F minor scale?", "G"],
    ["What is the 11th degree of the F minor scale?", "Bb"],
    ["What is the 13th degree of the F minor scale?", "Db"],
    ["What is the 2nd degree of the Db major scale?", "Eb"],
    ["What is the 3rd degree of the Db major scale?", "F"],
    ["What is the 4th degree of the Db major scale?", "Gb"],
    ["What is the 5th degree of the Db major scale?", "Ab"],
    ["What is the 6th degree of the Db major scale?", "Bb"],
    ["What is the 7th degree of the Db major scale?", "C"],
    ["What is the 9th degree of the Db major scale?", "Eb"],
    ["What is the 11th degree of the Db major scale?", "Gb"],
    ["What is the 13th degree of the Db major scale?", "Bb"],
    ["What is the 2nd degree of the Bb minor scale?", "C"],
    ["What is the 3rd degree of the Bb minor scale?", "Db"],
    ["What is the 4th degree of the Bb minor scale?", "Eb"],
    ["What is the 5th degree of the Bb minor scale?", "F"],
    ["What is the 6th degree of the Bb minor scale?", "Gb"],
    ["What is the 7th degree of the Bb minor scale?", "Ab"],
    ["What is the 9th degree of the Bb minor scale?", "C"],
    ["What is the 11th degree of the Bb minor scale?", "Eb"],
    ["What is the 13th degree of the Bb minor scale?", "Gb"],
    ["What is the 2nd degree of the Gb major scale?", "Ab"],
    ["What is the 3rd degree of the Gb major scale?", "Bb"],
    ["What is the 4th degree of the Gb major scale?", "Cb"],
    ["What is the 5th degree of the Gb major scale?", "Db"],
    ["What is the 6th degree of the Gb major scale?", "Eb"],
    ["What is the 7th degree of the Gb major scale?", "F"],
    ["What is the 9th degree of the Gb major scale?", "Ab"],
    ["What is the 11th degree of the Gb major scale?", "Cb"],
    ["What is the 13th degree of the Gb major scale?", "Eb"],
    ["What is the 2nd degree of the Eb minor scale?", "F"],
    ["What is the 3rd degree of the Eb minor scale?", "Gb"],
    ["What is the 4th degree of the Eb minor scale?", "Ab"],
    ["What is the 5th degree of the Eb minor scale?", "Bb"],
    ["What is the 6th degree of the Eb minor scale?", "Cb"],
    ["What is the 7th degree of the Eb minor scale?", "Db"],
    ["What is the 9th degree of the Eb minor scale?", "F"],
    ["What is the 11th degree of the Eb minor scale?", "Ab"],
    ["What is the 13th degree of the Eb minor scale?", "Cb"],
    [
        "What is the tonality of the chord built on the 1st degree of a major scale?",
        "M",
    ],
    [
        "What is the tonality of the chord built on the 2nd degree of a major scale?",
        "m",
    ],
    [
        "What is the tonality of the chord built on the 3rd degree of a major scale?",
        "m",
    ],
    [
        "What is the tonality of the chord built on the 4th degree of a major scale?",
        "M",
    ],
    [
        "What is the tonality of the chord built on the 5th degree of a major scale?",
        "M",
    ],
    [
        "What is the tonality of the chord built on the 6th degree of a major scale?",
        "m",
    ],
    [
        "What is the tonality of the chord built on the 7th degree of a major scale?",
        "dim",
    ],
    [
        "What is the tonality of the chord built on the 1st degree of a natural minor scale?",
        "m",
    ],
    [
        "What is the tonality of the chord built on the 2nd degree of a natural minor scale?",
        "dim",
    ],
    [
        "What is the tonality of the chord built on the 3rd degree of a natural minor scale?",
        "M",
    ],
    [
        "What is the tonality of the chord built on the 4th degree of a natural minor scale?",
        "m",
    ],
    [
        "What is the tonality of the chord built on the 5th degree of a natural minor scale?",
        "m",
    ],
    [
        "What is the tonality of the chord built on the 6th degree of a natural minor scale?",
        "M",
    ],
    [
        "What is the tonality of the chord built on the 7th degree of a natural minor scale?",
        "m",
    ],
    ["A to A# ascending is a ... interval", "m2"],
    ["A to B ascending is a ... interval", "M2"],
    ["A to C ascending is a ... interval", "m3"],
    ["A to C# ascending is a ... interval", "M3"],
    ["A to D ascending is a ... interval", "P4"],
    ["A to D# ascending is a ... interval", "TT"],
    ["A to E ascending is a ... interval", "P5"],
    ["A to F ascending is a ... interval", "m6"],
    ["A to F# ascending is a ... interval", "M6"],
    ["A to G ascending is a ... interval", "m7"],
    ["A to G# ascending is a ... interval", "M7"],
    ["A to Ab descending is a ... interval", "m2"],
    ["A to G descending is a ... interval", "M2"],
    ["A to Gb descending is a ... interval", "m3"],
    ["A to F descending is a ... interval", "M3"],
    ["A to E descending is a ... interval", "P4"],
    ["A to Eb descending is a ... interval", "TT"],
    ["A to D descending is a ... interval", "P5"],
    ["A to Db descending is a ... interval", "m6"],
    ["A to C descending is a ... interval", "M6"],
    ["A to B descending is a ... interval", "m7"],
    ["A to Bb descending is a ... interval", "M7"],
    ["The major key with one sharp note is ...", "G"],
    ["The major key with two sharp notes is ...", "D"],
    ["The major key with three sharp notes is ...", "A"],
    ["The major key with four sharp notes is ...", "E"],
    ["The major key with five sharp notes is ...", "B"],
    ["The major key with six sharp notes is ...", "F#"],
    ["The minor key with one sharp note is ...", "e"],
    ["The minor key with two sharp notes is ...", "b"],
    ["The minor key with three sharp notes is ...", "f#"],
    ["The minor key with four sharp notes is ...", "c#"],
    ["The minor key with five sharp notes is ...", "g#"],
    ["The minor key with six sharp notes is ...", "d#"],
    ["The major key with one flat note is ...", "F"],
    ["The major key with two flat notes is ...", "Bb"],
    ["The major key with three flat notes is ...", "Eb"],
    ["The major key with four flat notes is ...", "Ab"],
    ["The major key with five flat notes is ...", "Db"],
    ["The major key with six flat notes is ...", "Gb"],
    ["The minor key with one flat note is ...", "d"],
    ["The minor key with two flat notes is ...", "g"],
    ["The minor key with three flat notes is ...", "c"],
    ["The minor key with four flat notes is ...", "f"],
    ["The minor key with five flat notes is ...", "bb"],
    ["The minor key with six flat notes is ...", "eb"],
    ["The flat note in the key of F major is ...", "Bb"],
    ["The flat notes in the key of Bb major are ...", "Bb, Eb"],
    ["The flat notes in the key of Eb major are ...", "Bb, Eb, Ab"],
    ["The flat notes in the key of Ab major are ...", "Bb, Eb, Ab, Db"],
    ["The flat notes in the key of Db major are ...", "Bb, Eb, Ab, Db, Gb"],
    ["The flat notes in the key of Gb major are ...", "Bb, Eb, Ab, Db, Gb, Cb"],
    ["The sharp note in the key of G major is ...", "F#"],
    ["The sharp notes in the key of D major are ...", "F#, C#"],
    ["The sharp notes in the key of A major are ...", "F#, C#, G#"],
    ["The sharp notes in the key of E major are ...", "F#, C#, G#, D#"],
    ["The sharp notes in the key of B major are ...", "F#, C#, G#, D#, A#"],
    ["The sharp notes in the key of F# major are ...", "F#, C#, G#, D#, A#, E#"],
    ["The ... mode has a b3 and a b7 relative to the major scale", "dorian"],
    [
        "The ... mode has a b2, a b3, a b6, and a b7 relative to the major scale",
        "phrygian",
    ],
    ["The ... mode has a #4 relative to the major scale", "lydian"],
    ["The ... mode has a b7 relative to the major scale", "mixolydian"],
    ["The ... mode has a b3, a b6, and a b7 relative to the major scale", "aeolian"],
    [
        "The ... mode has a b2, a b3, a b5, a b6, and a b7 relative to the major scale",
        "lochrian",
    ],
    ["The relative minor of C major is ...", "a"],
    ["The relative minor of G major is ...", "e"],
    ["The relative minor of D major is ...", "b"],
    ["The relative minor of A major is ...", "f#"],
    ["The relative minor of E major is ...", "c#"],
    ["The relative minor of B major is ...", "g#"],
    ["The relative minor of F# major is ...", "d#"],
    ["The relative major of a minor is ...", "C"],
    ["The relative major of e minor is ...", "G"],
    ["The relative major of b minor is ...", "D"],
    ["The relative major of f# minor is ...", "A"],
    ["The relative major of c# minor is ...", "E"],
    ["The relative major of g# minor is ...", "B"],
    ["The relative major of d# minor is ...", "F#"],
    ["The relative minor of F major is ...", "d"],
    ["The relative minor of Bb major is ...", "g"],
    ["The relative minor of Eb major is ...", "c"],
    ["The relative minor of Ab major is ...", "f"],
    ["The relative minor of Db major is ...", "bb"],
    ["The relative minor of Gb major is ...", "eb"],
    ["The relative major of d minor is ...", "F"],
    ["The relative major of g minor is ...", "Bb"],
    ["The relative major of c minor is ...", "Eb"],
    ["The relative major of f minor is ...", "Ab"],
    ["The relative major of bb minor is ...", "Db"],
    ["The relative major of eb minor is ...", "Gb"],
    ["The Ionian mode is built on the ... degree of the major scale", "first"],
    ["The Dorian mode is built on the ... degree of the major scale", "second"],
    ["The Phrygian mode is built on the ... degree of the major scale", "third"],
    ["The Lydian mode is built on the ... degree of the major scale", "fourth"],
    ["The Mixolydian mode is built on the ... degree of the major scale", "fifth"],
    ["The Aeolian mode is built on the ... degree of the major scale", "sixth"],
    ["The Lochrian mode is built on the ... degree of the major scale", "seventh"],
    ["The Dorian mode contains ...", "b3, b7"],
    ["The Phrygian mode contains ...", "b2, b3, b6, b7"],
    ["The Lydian mode contains ...", "#4"],
    ["The Mixolydian mode contains ...", "b7"],
    ["The Aeolian mode contains ...", "b3, b6, b7"],
    ["The Lochrian mode contains ...", "b2, b3, b5, b6, b7"],
    ["The third of a Ab major chord is ...", "C"],
    ["The third of a A major chord is ...", "C#"],
    ["The third of a Bb major chord is ...", "D"],
    ["The third of a B major chord is ...", "D#"],
    ["The third of a C major chord is ...", "E"],
    ["The third of a Db major chord is ...", "F"],
    ["The third of a D major chord is ...", "F#"],
    ["The third of a Eb major chord is ...", "G"],
    ["The third of a E major chord is ...", "G#"],
    ["The third of a F major chord is ...", "A"],
    ["The third of a F# major chord is ...", "A#"],
    ["The third of a Gb major chord is ...", "Bb"],
    ["The third of a G major chord is ...", "B"],
    ["The fifth of a Ab major chord is ...", "Eb"],
    ["The fifth of a A major chord is ...", "E"],
    ["The fifth of a Bb major chord is ...", "F"],
    ["The fifth of a B major chord is ...", "F#"],
    ["The fifth of a C major chord is ...", "G"],
    ["The fifth of a Db major chord is ...", "Ab"],
    ["The fifth of a D major chord is ...", "A"],
    ["The fifth of a Eb major chord is ...", "Bb"],
    ["The fifth of a E major chord is ...", "B"],
    ["The fifth of a F major chord is ...", "C"],
    ["The fifth of a F# major chord is ...", "C#"],
    ["The fifth of a Gb major chord is ...", "Db"],
    ["The fifth of a G major chord is ...", "D"],
    ["The third of a A minor chord is ...", "C"],
    ["The third of a Bb minor chord is ...", "Db"],
    ["The third of a B minor chord is ...", "D"],
    ["The third of a C minor chord is ...", "Eb"],
    ["The third of a C# minor chord is ...", "E"],
    ["The third of a D minor chord is ...", "F"],
    ["The third of a D# minor chord is ...", "F#"],
    ["The third of a Eb minor chord is ...", "Gb"],
    ["The third of a E minor chord is ...", "G"],
    ["The third of a F minor chord is ...", "Ab"],
    ["The third of a F# minor chord is ...", "A"],
    ["The third of a G minor chord is ...", "Bb"],
    ["The third of a G# minor chord is ...", "B"],
    ["The fifth of a A minor chord is ...", "E"],
    ["The fifth of a Bb minor chord is ...", "F"],
    ["The fifth of a B minor chord is ...", "F#"],
    ["The fifth of a C minor chord is ...", "G"],
    ["The fifth of a C# minor chord is ...", "G#"],
    ["The fifth of a D minor chord is ...", "A"],
    ["The fifth of a D# minor chord is ...", "A#"],
    ["The fifth of a Eb minor chord is ...", "Bb"],
    ["The fifth of a E minor chord is ...", "B"],
    ["The fifth of a F minor chord is ...", "C"],
    ["The fifth of a F# minor chord is ...", "C#"],
    ["The fifth of a G minor chord is ...", "D"],
    ["The fifth of a G# minor chord is ...", "D#"],
    ["The third of a A diminished chord is ...", "C"],
    ["The third of a A# diminished chord is ...", "C#"],
    ["The third of a B diminished chord is ...", "D"],
    ["The third of a C diminished chord is ...", "Eb"],
    ["The third of a C# diminished chord is ...", "E"],
    ["The third of a D diminished chord is ...", "F"],
    ["The third of a D# diminished chord is ...", "F#"],
    ["The third of a E diminished chord is ...", "G"],
    ["The third of a F# diminished chord is ...", "A"],
    ["The third of a G diminished chord is ...", "Bb"],
    ["The third of a G# diminished chord is ...", "B"],
    ["The fifth of a A diminished chord is ...", "Eb"],
    ["The fifth of a A# diminished chord is ...", "E"],
    ["The fifth of a B diminished chord is ...", "F"],
    ["The fifth of a C diminished chord is ...", "Gb"],
    ["The fifth of a C# diminished chord is ...", "G"],
    ["The fifth of a D diminished chord is ...", "Ab"],
    ["The fifth of a D# diminished chord is ...", "A"],
    ["The fifth of a E diminished chord is ...", "Bb"],
    ["The fifth of a F# diminished chord is ...", "C"],
    ["The fifth of a G diminished chord is ...", "Db"],
    ["The fifth of a G# diminished chord is ...", "D"],
    # ["There are ... semitones in a perfect fourth interval", ""],
    # ["The note a perfect fifth above D is ...", "A"],
    # ["The major key where the chords Em and F#m are diatonic is ", "D"],
    # ["The minor key where the chords the chords Em and F#m are diatonic is", "B"],
    # ["The major key where F#m is the 6th chord is ...", "A"],
    # ["The minor key where F is the 6th chord is", "A"],
    # ["The seventh of a Ab major chord is ...", "D"],
    # ["The seventh of a A major chord is ...", ""],
    # ["The seventh of a Bb major chord is ...", ""],
    # ["The seventh of a B major chord is ...", ""],
    # ["The seventh of a C major chord is ...", ""],
    # ["The seventh of a Db major chord is ...", ""],
    # ["The seventh of a D major chord is ...", ""],
    # ["The seventh of a Eb major chord is ...", ""],
    # ["The seventh of a E major chord is ...", ""],
    # ["The seventh of a Fmajor chord is ...", ""],
    # ["The seventh of a F# major chord is ...", ""],
    # ["The seventh of a Gb major chord is ...", ""],
    # ["The seventh of a G major chord is ...", ""],
    # ["The seventh of a A minor chord is ...", ""],
    # ["The seventh of a Bb minor chord is ...", ""],
    # ["The seventh of a B minor chord is ...", ""],
    # ["The seventh of a C minor chord is ...", ""],
    # ["The seventh of a C# minor chord is ...", ""],
    # ["The seventh of a D minor chord is ...", ""],
    # ["The seventh of a D# minor chord is ...", ""],
    # ["The seventh of a Eb minor chord is ...", ""],
    # ["The seventh of a E minor chord is ...", ""],
    # ["The seventh of a F minor chord is ...", ""],
    # ["The seventh of a F# minor chord is ...", ""],
    # ["The seventh of a G minor chord is ...", ""],
    # ["The seventh of a G# minor chord is ...", ""],
    # ["The seventh of a A diminished chord is ...", ""],
    # ["The seventh of a A# diminished chord is ...", ""],
    # ["The seventh of a B diminished chord is ...", ""],
    # ["The seventh of a C diminished chord is ...", ""],
    # ["The seventh of a C# diminished chord is ...", ""],
    # ["The seventh of a D diminished chord is ...", ""],
    # ["The seventh of a D# diminished chord is ...", ""],
    # ["The seventh of a E diminished chord is ...", ""],
    # ["The fifth of a F diminished chord is ...", ""],
    # ["The seventh of a F# diminished chord is ...", ""],
    # ["The seventh of a G diminished chord is ...", ""],
    # ["The seventh of a G# diminished chord is ...", ""],
]

questions = sorted(questions, key=lambda _: random.random())
